### ISSUE TITLE
[Migration guidance] - Broken link

### ISSUE THREAD

**Issue by gidsg** [alphagov/paas-product-pages#332]
feedback for the GOV.UK PaaS migration guidance

Link [cloud migration expertise from the Digital Marketplace](https://www.digitalmarketplace.service.gov.uk/g-cloud/search?q=cloud%20migration) is broken.

**Comment by TheDoubleK** [comment]
Looks like this is the working link: https://www.applytosupply.digitalmarketplace.service.gov.uk/g-cloud/search?q=cloud%20migration
